/**
 * Types and helpers for the theory courses bundled under public/courses/.
 * The manifest (public/courses_files.json) is generated by
 * scripts/build-course-manifest.mjs and embeds each exercise's yaml metadata
 * so no YAML parsing happens at runtime.
 */

export interface CourseVideo {
    file: string;   // relative to the module dir, e.g. "videos/TheCircleOfFifths.mp4"
    title: string;
    /** When set, the video is streamed from YouTube instead of the local file. */
    youtubeId?: string;
}

export interface CourseExercise {
    id: string;
    type: string;
    title: string;
    instructions: string;
    key: string;    // music21 style: uppercase = major, lowercase = minor, "-" = flat
    dir: string;    // relative to the module dir, e.g. "exercises/fifth-kinship/<id>"
    slots: number;  // number of chord-events the student must fill
}

export interface CourseModule {
    id: string;
    number: number;
    title: string;
    videos: CourseVideo[];
    exercises: CourseExercise[];
}

export interface Course {
    id: string;
    title: string;
    path: string;   // relative to public/, e.g. "courses/harmony-1"
    modules: CourseModule[];
}

export interface CoursesManifest {
    courses: Course[];
}

export async function fetchCoursesManifest(): Promise<CoursesManifest> {
    const res = await fetch('/courses_files.json');
    if (!res.ok) throw new Error(`Failed to load course manifest (${res.status})`);
    return res.json();
}

export function moduleFileUrl(course: Course, module: CourseModule, relative: string): string {
    return `/${course.path}/${module.id}/${relative}`;
}

export function exerciseFileUrl(course: Course, module: CourseModule, exercise: CourseExercise, file: string): string {
    return moduleFileUrl(course, module, `${exercise.dir}/${file}`);
}

// ---------------------------------------------------------------------------
// Progress — persisted per browser in localStorage.

export interface TheoryProgress {
    exercises: Record<string, { completedAt: number }>;
    videos: Record<string, { watchedAt: number }>;
}

const PROGRESS_KEY = 'theory-progress-v1';

export function videoProgressKey(course: Course, module: CourseModule, video: CourseVideo): string {
    return `${course.id}/${module.id}/${video.file}`;
}

export function loadProgress(): TheoryProgress {
    try {
        const raw = localStorage.getItem(PROGRESS_KEY);
        if (raw) {
            const parsed = JSON.parse(raw);
            return { exercises: parsed.exercises ?? {}, videos: parsed.videos ?? {} };
        }
    } catch { /* fall through to empty */ }
    return { exercises: {}, videos: {} };
}

export function saveProgress(progress: TheoryProgress): void {
    try {
        localStorage.setItem(PROGRESS_KEY, JSON.stringify(progress));
    } catch { /* storage full/blocked — progress just won't persist */ }
}
